server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
      #http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true