server:
  port: 8761

eureka:
  instance:
    hostname: localhost #discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/ 
      #http://discovery:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true