server:
  port: 10001 #10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: discovery-microservice.azurewebsites.net    
     #gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-microservice.azurewebsites.net/eureka/
      #http://localhost:8761/eureka/
      # http://discovery:8761/eureka/